# SPDX-License-Identifier: Apache-2.0
"""Tests for the disclosure detector.

Two things are being pinned here.

**Both directions are reported.** `disclosure_missing` when nothing matched and
`disclosure_present` when something did. The positive is the load-bearing one: an
auditor asking "did the assistant disclose itself?" must be able to read the answer out
of the record, not infer it from an absence, because an absence is also what a detector
that never ran produces.

**Word boundaries.** A substring search for "ai" matches "said", "again" and "email". A
regression there turns this detector into a no-op that reports success on every output,
which is the worst available failure, so it has its own tests.

All 26 languages are exercised, because a phrasings file with an untested language is a
phrasings file with a typo in it.
"""

from __future__ import annotations

import pytest

from flowx_border.detectors.base import Context, DetectorConfig
from flowx_border.detectors.disclosure import (
    DisclosureDataError,
    DisclosureDetector,
    load_phrasings,
    normalise,
    unreviewed_languages,
)
from flowx_border.types import Finding

DETECTOR = DisclosureDetector()
CFG = DetectorConfig(on_fail="flag")
CTX = Context()


def run(text: str, cfg: DetectorConfig = CFG) -> list[Finding]:
    return DETECTOR.run(text, cfg, CTX)


def labels(text: str, cfg: DetectorConfig = CFG) -> list[str]:
    return [finding.label for finding in run(text, cfg)]


# ------------------------------------------------------------------ the two findings


def test_a_plain_answer_with_no_disclosure_is_reported_missing() -> None:
    # This is the phase 2 definition of done.
    assert labels("Your balance is 412 EUR as of this morning.") == [
        "disclosure_missing"
    ]


def test_an_answer_carrying_a_disclosure_is_reported_present() -> None:
    assert labels("This response was generated by AI. Your balance is 412 EUR.") == [
        "disclosure_present"
    ]


def test_the_two_findings_are_mutually_exclusive() -> None:
    for text in ("no disclosure at all here", "I am an AI assistant."):
        assert len(labels(text)) == 1, text


def test_a_missing_disclosure_takes_its_action_from_the_policy() -> None:
    assert run("nothing here", DetectorConfig(on_fail="block"))[0].action == "block"
    assert run("nothing here", DetectorConfig(on_fail="rewrite"))[0].action == "rewrite"


def test_a_present_disclosure_is_always_logged_and_never_the_policy_action() -> None:
    # on_fail describes what to do about a missing disclosure. Applying it to a present
    # one would block outputs for complying, which is the opposite of the intent.
    finding = run("Generated by AI.", DetectorConfig(on_fail="block"))[0]
    assert finding.action == "log"


def test_a_present_disclosure_does_not_change_the_verdict() -> None:
    # `log` maps to `allow` in the engine, so recording the positive is free.
    from flowx_border.engine import run_scan
    from flowx_border.policy import Policy

    policy = Policy(
        policy_id="t",
        version=1,
        fail_mode=dict.fromkeys(("T0", "T1", "T2", "T3"), "open"),
        detectors={},
    )
    decision = run_scan(
        "Generated by AI. All good.", "output", policy, None, {"disclosure": DETECTOR}
    )
    assert decision.verdict == "allow"
    assert [f.label for f in decision.evidence.finding_summary] == [
        "disclosure_present"
    ]


def test_neither_finding_carries_a_span() -> None:
    # Missing: there is no offset for a thing that is not there, and pointing at the end
    # would imply that is where it belongs, which is not this detector's call. Present:
    # the offset would index the normalised text, not the caller's string.
    for text in ("nothing here", "Generated by AI."):
        assert run(text)[0].span is None


# --------------------------------------------------------------------- word boundaries


@pytest.mark.parametrize(
    "text",
    [
        "He said the balance was wrong.",
        "Please try again later.",
        "Send it to my email address.",
        "The claim was paid in Dubai last year.",
        "Your certificate has been mailed.",
        "Retrieved from the domain registrar.",
    ],
)
def test_a_word_merely_containing_ai_is_not_a_disclosure(text: str) -> None:
    # The regression that would make this detector useless while looking like it passes.
    assert labels(text) == ["disclosure_missing"], text


def test_a_hyphenated_disclosure_still_matches() -> None:
    assert labels("This is an AI-generated summary.") == ["disclosure_present"]


def test_matching_ignores_case() -> None:
    for text in ("GENERATED BY AI", "generated by ai", "Generated By Ai"):
        assert labels(f"{text}. Your balance is fine.") == ["disclosure_present"], text


def test_matching_survives_collapsed_whitespace() -> None:
    assert labels("generated    by\n\tai, see below") == ["disclosure_present"]


def test_matching_survives_a_decomposed_diacritic() -> None:
    # The same Romanian word arrives precomposed or decomposed depending on the platform
    # that produced it, and two spellings of one word must not be two results.
    import unicodedata

    text = "Acest răspuns a fost generat automat."
    assert labels(text) == ["disclosure_present"]
    assert labels(unicodedata.normalize("NFD", text)) == ["disclosure_present"]


# --------------------------------------------------------------------- all 26 languages


DISCLOSED = {
    "en": "This answer was generated by AI. The rest is detail.",
    "ro": "Acest răspuns a fost generat automat de inteligență artificială.",
    "pl": "Ta odpowiedź została wygenerowana przez sztuczną inteligencję.",
    "hu": "Ezt a választ mesterséges intelligencia készítette.",
    "tr": "Bu yanıt yapay zeka tarafından oluşturulmuştur.",
    "az": "Bu cavab süni intellekt tərəfindən hazırlanmışdır.",
    "bg": "Този отговор е генериран от изкуствен интелект.",
    "cs": "Tato odpověď byla vygenerována umělou inteligencí.",
    "da": "Dette svar er genereret af kunstig intelligens.",
    "de": "Diese Antwort wurde von einer KI erstellt.",
    "el": "Αυτή η απάντηση δημιουργήθηκε από τεχνητή νοημοσύνη.",
    "es": "Esta respuesta ha sido generada por inteligencia artificial.",
    "et": "See vastus on tehisintellekti loodud.",
    "fi": "Tämä vastaus on tekoälyn luoma.",
    "fr": "Cette réponse a été produite par une intelligence artificielle.",
    "ga": "Cruthaíodh an freagra seo le intleacht shaorga.",
    "hr": "Ovaj odgovor generirala je umjetna inteligencija.",
    "it": "Questa risposta è stata prodotta da intelligenza artificiale.",
    "lt": "Šį atsakymą sukūrė dirbtinis intelektas.",
    "lv": "Šo atbildi izveidojis mākslīgais intelekts.",
    "mt": "Din it-tweġiba ġiet iġġenerata minn intelliġenza artifiċjali.",
    "nl": "Dit antwoord is gegenereerd door kunstmatige intelligentie.",
    "pt": "Esta resposta foi gerada por inteligência artificial.",
    "sk": "Táto odpoveď bola vygenerovaná umelou inteligenciou.",
    "sl": "Ta odgovor je ustvarila umetna inteligenca.",
    "sv": "Detta svar har genererats av artificiell intelligens.",
}

# Ordinary answers with no disclosure, in the same languages. English-only negatives
# would mean the boundary logic is only tested for one script.
NOT_DISCLOSED = {
    "en": "Your balance is 412 EUR as of this morning.",
    "ro": "Soldul dumneavoastră este de 412 EUR în această dimineață.",
    "pl": "Twoje saldo wynosi 412 EUR na dziś rano.",
    "hu": "Az egyenlege ma reggel 412 EUR.",
    "tr": "Bakiyeniz bu sabah itibarıyla 412 EUR.",
    "az": "Bu səhər hesabınızdaki qalıq 412 EUR-dur.",
    "bg": "Салдото ви е 412 EUR към тази сутрин.",
    "cs": "Váš zůstatek je dnes ráno 412 EUR.",
    "da": "Din saldo er 412 EUR i morges.",
    "de": "Ihr Kontostand beträgt heute Morgen 412 EUR.",
    "el": "Το υπόλοιπό σας είναι 412 EUR σήμερα το πρωί.",
    "es": "Su saldo es de 412 EUR esta mañana.",
    "et": "Teie saldo on täna hommikul 412 EUR.",
    "fi": "Saldosi on tänä aamuna 412 EUR.",
    "fr": "Votre solde est de 412 EUR ce matin.",
    "ga": "Is é 412 EUR an t-iarmhéid atá agat ar maidin.",
    "hr": "Vaš saldo jutros iznosi 412 EUR.",
    "it": "Il suo saldo è di 412 EUR questa mattina.",
    "lt": "Jūsų balansas šį rytą yra 412 EUR.",
    "lv": "Jūsu atlikums šorīt ir 412 EUR.",
    "mt": "Il-bilanċ tiegħek dalgħodu huwa 412 EUR.",
    "nl": "Uw saldo is vanmorgen 412 EUR.",
    "pt": "O seu saldo é de 412 EUR esta manhã.",
    "sk": "Váš zostatok je dnes ráno 412 EUR.",
    "sl": "Vaše stanje je danes zjutraj 412 EUR.",
    "sv": "Ditt saldo är 412 EUR i morse.",
}


@pytest.mark.parametrize("code", sorted(DISCLOSED))
def test_a_disclosure_in_each_language_is_found(code: str) -> None:
    assert labels(DISCLOSED[code]) == ["disclosure_present"], code


@pytest.mark.parametrize("code", sorted(NOT_DISCLOSED))
def test_an_ordinary_answer_in_each_language_is_reported_missing(code: str) -> None:
    assert labels(NOT_DISCLOSED[code]) == ["disclosure_missing"], code


def test_the_fixtures_cover_every_language_in_the_data_file() -> None:
    # A phrasings file with an untested language is a phrasings file with a typo in it.
    assert set(load_phrasings()) == set(DISCLOSED) == set(NOT_DISCLOSED)


def test_every_language_the_project_claims_has_phrasings() -> None:
    claimed = {
        "bg",
        "cs",
        "da",
        "de",
        "el",
        "en",
        "es",
        "et",
        "fi",
        "fr",
        "ga",
        "hr",
        "hu",
        "it",
        "lt",
        "lv",
        "mt",
        "nl",
        "pl",
        "pt",
        "ro",
        "sk",
        "sl",
        "sv",
        "tr",
        "az",
    }
    assert claimed == set(load_phrasings())


def test_the_unreviewed_languages_are_reported_rather_than_hidden() -> None:
    # 26 languages is not 26 verified languages, and a coverage table has to be able to
    # say so. When a native speaker reviews one, this test records the change.
    assert len(unreviewed_languages()) == 26


# --------------------------------------------------------------------------- options


def test_a_policy_can_restrict_the_accepted_languages() -> None:
    # A product answering only in Romanian does not want an English phrase in its output
    # to count as its disclosure.
    romanian_only = DetectorConfig(options={"languages": ["ro"]})
    assert labels("This was generated by AI.", romanian_only) == ["disclosure_missing"]
    assert labels("Generat automat de AI.", romanian_only) == ["disclosure_present"]


def test_restricting_to_an_unknown_language_raises_rather_than_checking_nothing() -> (
    None
):
    with pytest.raises(DisclosureDataError, match="no phrasings"):
        DETECTOR.run("x", DetectorConfig(options={"languages": ["xx"]}), CTX)


def test_a_policy_can_add_house_wording() -> None:
    cfg = DetectorConfig(options={"extra_phrasings": ["produced by our virtual agent"]})
    assert labels("Produced by our virtual agent.", cfg) == ["disclosure_present"]
    assert labels("Produced by our virtual agent.") == ["disclosure_missing"]


def test_extra_wording_is_matched_on_boundaries_too() -> None:
    cfg = DetectorConfig(options={"extra_phrasings": ["bot"]})
    assert labels("Bot.", cfg) == ["disclosure_present"]
    assert labels("I rebooted the router.", cfg) == ["disclosure_missing"]


def test_a_short_output_can_be_exempted_but_only_explicitly() -> None:
    assert labels("Yes.") == ["disclosure_missing"]
    assert labels("Yes.", DetectorConfig(options={"min_chars": 20})) == []


def test_the_default_checks_every_length() -> None:
    # A silent length exemption is how a disclosure requirement quietly stops applying.
    assert DetectorConfig().options.get("min_chars") is None
    assert labels("Ok") == ["disclosure_missing"]


# --------------------------------------------------------------------------- plumbing


def test_normalise_collapses_and_casefolds() -> None:
    assert normalise("  Generated   BY\n AI  ") == "generated by ai"


def test_an_empty_output_is_a_missing_disclosure_not_an_error() -> None:
    assert labels("") == ["disclosure_missing"]


def test_the_detector_matches_the_catalogue() -> None:
    from flowx_border.detectors.catalogue import CATALOGUE

    spec = CATALOGUE["disclosure"]
    assert (DETECTOR.id, DETECTOR.tier) == ("disclosure", spec.tier)
    assert DETECTOR.sides == spec.sides


def test_warm_is_idempotent() -> None:
    DETECTOR.warm()
    DETECTOR.warm()
    assert labels("Generated by AI.") == ["disclosure_present"]


def test_findings_never_carry_the_output_text() -> None:
    for text in ("Generated by AI, balance 412 EUR.", "balance 412 EUR"):
        for finding in run(text):
            assert "412" not in finding.model_dump_json()
