# SPDX-License-Identifier: Apache-2.0
"""Constraint 1: a scan works with the network interface down.

The autouse guard in conftest.py blocks egress for the whole suite, so in a sense every
test is an offline test. This file exists because that is exactly the sort of protection
that quietly stops working. The guard is one fixture; if it were disabled, mis-scoped, or
made too narrow, nothing else in the suite would notice, and the claim "works offline"
would keep being made.

So these tests are deliberately paranoid in a way the others are not. They assert on the
guard being active, they scan through the whole public API with every loaded detector, and
they check the one path that would plausibly reach out: a detector's `run` calling something
that resolves a model.

The division of labour, worth keeping straight:

    conftest.py             blocks egress for every test
    test_no_network_guard   proves the block works and what it does and does not cover
    test_offline.py         proves a real scan completes under it, which is the claim

`HF_HUB_OFFLINE=1` is set as well, because huggingface-hub will otherwise make a
revalidation request for a file it already has, and a cached file plus a HEAD request is not
the same thing as offline.
"""

from __future__ import annotations

import os
import socket

import pytest

os.environ.setdefault("HF_HUB_OFFLINE", "1")

from flowx_border import load_policy, scan_input, scan_output
from flowx_border.detectors.base import Context
from flowx_border.detectors.catalogue import CATALOGUE
from flowx_border.policy import DetectorPolicy, Policy
from flowx_border.registry import loaded_detectors

MARKER = "Ionescu Bogdan, marie.dubois@bank.fr, AKIAIOSFODNN7EXAMPLE, +40 721 234 567"


def every_loaded_detector() -> Policy:
    """A policy enabling every detector this install can actually provide.

    Enabling one that is not loaded would raise DetectorUnavailableError before any scan
    happened, which would make this file pass for the wrong reason.
    """
    available = set(loaded_detectors())
    return Policy(
        policy_id="offline",
        version=1,
        fail_mode=dict.fromkeys(("T0", "T1", "T2", "T3"), "open"),
        detectors={
            name: DetectorPolicy(enabled=name in available, on_fail="redact")
            for name in CATALOGUE
        },
    )


# ------------------------------------------------------------------ the guard is on


def test_the_offline_guard_is_actually_active() -> None:
    """Asserted first, so that everything below means something.

    Without this, a broken guard would make every test in this file pass while proving
    nothing at all.
    """
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        with pytest.raises(RuntimeError, match="network access during a test"):
            sock.connect(("huggingface.co", 443))
    with pytest.raises(RuntimeError, match="network access during a test"):
        socket.getaddrinfo("huggingface.co", 443)


def test_hub_offline_is_set_so_a_cached_file_is_not_revalidated() -> None:
    # A cached file plus a HEAD request is not offline.
    assert os.environ.get("HF_HUB_OFFLINE") == "1"


# ------------------------------------------------------------------------ real scans


def test_scan_input_completes_offline() -> None:
    decision = scan_input(MARKER, every_loaded_detector())
    assert decision.evidence.record_id
    assert decision.verdict in ("allow", "flag", "redact", "block")


def test_scan_output_completes_offline() -> None:
    decision = scan_output(
        "Your advisor is Marie Dubois.",
        every_loaded_detector(),
        Context(sources=("Your advisor is Marie Dubois.",)),
    )
    assert decision.evidence.record_id


def test_every_loaded_detector_runs_offline() -> None:
    """Each one individually, so a failure names the detector rather than the scan.

    This is the test that would catch a new detector resolving its model inside `run`
    instead of `warm`, which is the single easiest way to break constraint 1.
    """
    from flowx_border.detectors.base import DetectorConfig

    detectors = loaded_detectors()
    assert detectors, "no detectors loaded, so this file would prove nothing"

    for name, detector in sorted(detectors.items()):
        detector.warm()
        side_text = MARKER if "input" in CATALOGUE[name].sides else "Generated by AI."
        findings = detector.run(
            side_text, DetectorConfig(on_fail="flag"), Context(sources=("a source",))
        )
        assert isinstance(findings, list), name


def test_a_redaction_happens_offline() -> None:
    # Not just "did not crash": the library has to do its job with no network.
    decision = scan_input(
        f"my key is AKIAIOSFODNN7EXAMPLE and I am {MARKER}", every_loaded_detector()
    )
    assert "AKIA" not in decision.text
    assert decision.text != decision.original_text


def test_the_evidence_record_is_complete_offline() -> None:
    # The record is the product. It must not degrade when the network is down.
    decision = scan_input(MARKER, every_loaded_detector())
    record = decision.evidence
    assert record.policy_hash and len(record.policy_hash) == 64
    assert record.input_hash and len(record.input_hash) == 64
    assert record.library_version
    assert record.detectors, "the record attests no detectors"


def test_warming_twice_offline_is_fine() -> None:
    # A second warm must be a cache hit rather than a second resolve, or a restart-heavy
    # deployment would need the network on every boot.
    for detector in loaded_detectors().values():
        detector.warm()
        detector.warm()


def test_a_policy_loads_from_disk_offline() -> None:
    from pathlib import Path

    policies = Path(__file__).resolve().parent.parent / "policies"
    policy = load_policy(policies / "default.yaml")
    assert policy.policy_id == "default"


def test_signing_works_offline() -> None:
    # The caller's key, no key server, no network. Worth asserting because a signing
    # implementation that phoned a KMS would be a constraint 1 violation hiding in the
    # evidence layer.
    ed25519 = pytest.importorskip("cryptography.hazmat.primitives.asymmetric.ed25519")

    from flowx_border.evidence import sign_record, verify_record

    decision = scan_input(MARKER, every_loaded_detector())
    private = ed25519.Ed25519PrivateKey.generate()
    signed = sign_record(decision.evidence, private)
    assert verify_record(signed, private.public_key()) is True
