# SPDX-License-Identifier: Apache-2.0
"""Tests for `language_id`.

**Every sentence here was written by hand and none of it is in the profile corpus.**
That is the point rather than a detail. The profiles are built by
`border_train.build_language_profiles` from ten task corpora, almost all generated by
one model, so scoring the detector on a held-out slice of that corpus would measure
whether the profile matches its own generator. It would pass and mean nothing, which
is the failure this project has recorded eight times.

So the fixtures below are ordinary administrative sentences in all 26 languages, written
for this file. If the detector ever stops passing them, the profile has drifted from the
languages rather than from the corpus.
"""

from __future__ import annotations

import pytest

from flowx_border.detectors.base import INPUT, OUTPUT, Context, DetectorConfig
from flowx_border.detectors.language_id import (
    DEFAULT_MIN_MARGIN,
    LanguageIdDetector,
    identify,
)
from flowx_border.detectors.multilingual import LANGUAGES

#: One hand-written sentence per supported language. Deliberately mundane and of similar
#: length, so a pass is about the language and not about the topic.
SENTENCES: dict[str, str] = {
    "en": "The committee will meet again after the summer to review it.",
    "ro": "Comisia se va reuni din nou dupa vara pentru a analiza cererea.",
    "de": "Der Ausschuss wird nach der Sommerpause erneut zusammentreten.",
    "fr": "Le comite se reunira apres les vacances pour examiner la demande.",
    "es": "La comision se reunira de nuevo despues del verano para revisarlo.",
    "it": "Il comitato si riunira dopo la pausa estiva per esaminare la richiesta.",
    "pt": "A comissao reunira novamente apos o verao para analisar o pedido.",
    "nl": "De commissie komt na het zomerreces opnieuw bijeen om het te bespreken.",
    "sv": "Kommitten kommer att sammantrada igen efter sommaren for att granska.",
    "da": "Udvalget vil traede sammen igen efter sommerferien for at se pa det.",
    "fi": "Valiokunta kokoontuu uudelleen kesätauon jälkeen käsittelemään asian.",
    "et": "Komisjon tuleb pärast suvepuhkust uuesti kokku, et taotlust vaadata.",
    "lv": "Komiteja pēc vasaras pārtraukuma atkal sanāks, lai izskatītu lūgumu.",
    "lt": "Komitetas po vasaros atostogų vėl susirinks apsvarstyti prašymo.",
    "pl": "Komisja zbierze się ponownie po wakacjach, aby rozpatrzyć wniosek.",
    "cs": "Výbor se po letní přestávce znovu sejde, aby projednal ten návrh.",
    "sk": "Výbor sa po letnej prestávke opäť zíde, aby prerokoval ten návrh.",
    "sl": "Odbor se bo po poletnem premoru znova sestal in obravnaval predlog.",
    "hr": "Odbor će se nakon ljetne stanke ponovno sastati i razmotriti to.",
    "hu": "A bizottság a nyári szünet után ismét összeül a kérelem ügyében.",
    "bg": "Комисията ще заседава отново след лятото, за да разгледа молбата.",
    "el": "Η επιτροπή θα συνεδριάσει ξανά μετά το καλοκαίρι για την αίτηση.",
    "ga": "Tiocfaidh an coiste le chéile arís tar éis an tsamhraidh chun é a mheas.",
    "mt": "Il-kumitat se jerġa' jiltaqa' wara s-sajf biex jeżamina t-talba.",
    "tr": "Komisyon yaz tatilinden sonra basvuruyu incelemek icin toplanacak.",
    "az": "Komissiya yay tətilindən sonra müraciəti nəzərdən keçirmək üçün toplaşacaq.",
}

FLAG = DetectorConfig(on_fail="flag", threshold=0.5)


def test_a_sentence_is_written_for_every_supported_language() -> None:
    """English plus five is a bug, per CLAUDE.md. All 26 or the file is incomplete."""
    assert set(SENTENCES) == set(LANGUAGES)


@pytest.mark.parametrize("code", sorted(SENTENCES))
def test_each_language_is_identified_from_text_the_profile_never_saw(code: str) -> None:
    got, margin = identify(SENTENCES[code])
    assert got == code, f"{code}: got {got} at margin {margin:.3f}"
    assert margin >= DEFAULT_MIN_MARGIN


def test_text_too_short_to_judge_is_refused_rather_than_guessed() -> None:
    """The case every language identifier gets wrong and few admit to.

    `Merci` is French, Romanian and Catalan. A detector that names one of them is
    guessing, and a guess in an evidence record is worse than an abstention because it
    reads exactly like a measurement.
    """
    for text in ("Ok", "Merci", "Da", "Nu", "Ja bitte"):
        got, _ = identify(text)
        assert got is None, f"{text!r} was called {got}"


def test_an_unsupported_language_is_uncertain_rather_than_the_nearest_of_26() -> None:
    """Japanese is not one of the 26, so naming any of them would be a wrong answer.

    This is the difference between a detector that knows its own scope and one that
    always returns something. Scored against 26 European profiles, Japanese has no
    winner, and reporting the closest would put a confident falsehood in a record.
    """
    for text in (
        "これは日本語の文章です。委員会は夏休みの後に再び開催されます。",
        "위원회는 여름 휴가 후에 다시 소집되어 제안을 검토할 것입니다.",
        "ستجتمع اللجنة مرة أخرى بعد العطلة الصيفية لمراجعة الاقتراح.",
    ):
        got, margin = identify(text)
        assert got is None, f"called {got} at margin {margin:.3f}"


def test_it_never_returns_nothing() -> None:
    """CLAUDE.md's third rule. Unconfigured is a finding, not silence."""
    detector = LanguageIdDetector()
    detector.warm()

    # Nothing configured: it still says which language it found and that it was asked
    # nothing about it.
    findings = detector.run(SENTENCES["ro"], FLAG, Context())
    assert findings, "an unconfigured run returned no findings at all"
    assert any(f.label == "language_ro" for f in findings)
    assert all(f.action == "log" for f in findings)

    # Too short to judge: also a finding.
    short = detector.run("Ok", FLAG, Context())
    assert [f.label for f in short] == ["language_uncertain"]
    assert short[0].action == "log"


def test_a_disallowed_language_is_reported_at_the_policy_action() -> None:
    detector = LanguageIdDetector()
    cfg = DetectorConfig(
        on_fail="block", threshold=0.5, options={"allowed": ["en", "ro"]}
    )

    allowed = detector.run(SENTENCES["ro"], cfg, Context())
    assert not [f for f in allowed if f.label.startswith("language_not_allowed")]

    refused = detector.run(SENTENCES["de"], cfg, Context())
    hit = [f for f in refused if f.label.startswith("language_not_allowed")]
    assert hit and hit[0].label == "language_not_allowed"
    assert hit[0].action == "block"


def test_an_answer_in_a_different_language_from_the_prompt_is_reported() -> None:
    """The LanguageSame question, which needs the caller to say what the prompt was."""
    detector = LanguageIdDetector()
    cfg = DetectorConfig(on_fail="flag", threshold=0.5, options={"match_input": True})

    same = detector.run(
        SENTENCES["ro"], cfg, Context(metadata={"input_language": "ro"})
    )
    assert not [f for f in same if f.label.startswith("language_differs")]

    drifted = detector.run(
        SENTENCES["de"], cfg, Context(metadata={"input_language": "ro"})
    )
    hit = [f for f in drifted if f.label.startswith("language_differs_from_input")]
    assert hit and hit[0].label == "language_differs_from_input"


def test_asking_to_match_an_input_language_nobody_supplied_says_so() -> None:
    """Not a pass. The check was configured, could not run, and says which."""
    detector = LanguageIdDetector()
    cfg = DetectorConfig(on_fail="flag", threshold=0.5, options={"match_input": True})
    findings = detector.run(SENTENCES["ro"], cfg, Context())
    assert [f.label for f in findings] == ["language_ro", "input_language_unknown"]
    assert findings[0].action == "log"


def test_it_is_registered_on_both_sides_at_t1() -> None:
    from flowx_border.detectors.catalogue import CATALOGUE

    spec = CATALOGUE["language_id"]
    assert spec.tier == "T1"
    assert spec.sides == frozenset({INPUT, OUTPUT})
    # A rule-sized budget: trigrams over a packaged table, and it has to answer
    # before any encoder runs.
    assert spec.budget_ms == 5.0
