# SPDX-License-Identifier: Apache-2.0
"""The published performance file has to be honest, and these tests are what enforce it.

`docs/reference/performance.json` is generated by `benchmarks/collect.py` and has two
consumers with different failure modes. The README quotes it, and a stale README is
embarrassing. The landing page renders it, and a marketing page claiming `F1 1.000` for
Danish on the strength of four test examples is worse than embarrassing.

So this file does not check that the generator ran. It checks the properties that make a
number safe to publish:

    every score carries its sample size a detector that is not built has no numbers at
    all, rather than last week's a score of zero explains itself a thin sample says it
    is thin the markdown and the JSON agree

The generator is written to produce all of that. These tests exist because a later
change to the generator, or a hand edit to the file, would not otherwise be caught until
someone had already published the result.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from flowx_border.detectors.catalogue import CATALOGUE

REPO = Path(__file__).resolve().parent.parent
PERFORMANCE = REPO / "docs" / "reference" / "performance.json"
PERFORMANCE_MD = REPO / "docs" / "reference" / "performance.md"

#: Mirrors benchmarks/collect.py. Duplicated deliberately: if the generator's idea of
#: thin support drifts, this file should fail rather than silently follow it.
THIN_SUPPORT = 10


@pytest.fixture(scope="module")
def performance() -> dict[str, Any]:
    if not PERFORMANCE.exists():
        pytest.skip(
            "docs/reference/performance.json is absent. Generate it with "
            "`uv run python benchmarks/collect.py --artifacts <dir>`."
        )
    loaded: dict[str, Any] = json.loads(PERFORMANCE.read_text(encoding="utf-8"))
    return loaded


def scored(performance: dict[str, Any]) -> dict[str, Any]:
    """Only the detectors that actually carry numbers."""
    return {
        name: entry
        for name, entry in performance["detectors"].items()
        if entry.get("metrics")
    }


# ------------------------------------------------------- agrees with the code


def test_every_catalogued_detector_appears(performance: dict[str, Any]) -> None:
    # A detector missing from the file is a detector a reader will assume does not
    # exist.
    assert set(performance["detectors"]) == set(CATALOGUE)


def test_no_entry_describes_a_detector_that_does_not_exist(
    performance: dict[str, Any],
) -> None:
    assert not set(performance["detectors"]) - set(CATALOGUE)


def test_tier_and_sides_match_the_catalogue(performance: dict[str, Any]) -> None:
    # The catalogue is the authority. A file that disagrees with it is describing a
    # different library from the one that will run.
    for name, entry in performance["detectors"].items():
        spec = CATALOGUE[name]
        assert entry["tier"] == spec.tier, name
        assert set(entry["sides"]) == set(spec.sides), name
        assert entry["budget_ms"] == spec.budget_ms, name


# ------------------------------------------------ no number without its n


def test_every_language_score_carries_its_sample_size(
    performance: dict[str, Any],
) -> None:
    """The single most important assertion in this file.

    A renderer that has the score and the sample size in the same object can only omit
    the sample size on purpose. A renderer given a bare float cannot do anything else.

    `n` may be null, because one evaluation genuinely records no count and inventing one
    would be worse than admitting it. Null is not a loophole: the next assertion
    requires a note saying so, so a null reaches the reader as "unverified" rather than
    as blank.
    """
    for name, entry in scored(performance).items():
        for code, row in entry["metrics"]["per_language"].items():
            assert "score" in row, f"{name}/{code} has no score"
            assert "n" in row, f"{name}/{code} has a score with no sample size"
            assert row["n"] is None or isinstance(row["n"], int), (
                f"{name}/{code} sample size is neither a count nor an admission"
            )


def test_a_missing_sample_size_is_declared_rather_than_left_blank(
    performance: dict[str, Any],
) -> None:
    """The rule that keeps `n: null` from being a way round the previous test."""
    for name, entry in scored(performance).items():
        uncounted = entry["metrics"]["languages_without_a_count"]
        for code, row in entry["metrics"]["per_language"].items():
            if row["n"] is None:
                assert code in uncounted, f"{name}/{code} is uncounted but not listed"
                joined = " ".join(row.get("notes", []))
                assert "did not record" in joined, (
                    f"{name}/{code} has no sample size and does not say so"
                )
        if uncounted:
            assert entry["caveats"], f"{name} has uncounted languages and no caveat"


def test_what_the_count_counts_is_stated(performance: dict[str, Any]) -> None:
    """In the source files `support` is positives, not the total, and they differ.

    A reader told "5 examples" when 5 was the positive count inside a set of 40 has been
    given the wrong number rather than an imprecise one, so the meaning travels with it.
    """
    for name, entry in scored(performance).items():
        assert entry["metrics"]["n_means"] in (
            "positive examples",
            "examples evaluated",
            "not recorded",
        ), name


def test_the_aggregate_says_how_many_examples_it_rests_on(
    performance: dict[str, Any],
) -> None:
    for name, entry in scored(performance).items():
        metrics = entry["metrics"]
        counted = [
            row["n"] for row in metrics["per_language"].values() if row["n"] is not None
        ]
        if not counted:
            # None rather than 0, because a zero would read as "measured on nothing",
            # which is a claim about the evaluation rather than the absence of one.
            assert metrics["total_examples"] is None, name
            continue
        assert metrics["total_examples"] == sum(counted), name
        assert metrics["total_examples"] > 0, name


def test_the_metric_is_named_rather_than_assumed(performance: dict[str, Any]) -> None:
    """F1 and exact-match accuracy are not interchangeable.

    A reader comparing 0.96 against 0.88 across two detectors needs to know whether
    those are the same measurement. They are not always: a single-label head reports
    accuracy because P/R/F1 over "did it fire" is 1.000 by construction for argmax.
    """
    for name, entry in scored(performance).items():
        assert entry["metrics"]["metric"] in (
            "f1",
            "exact_match_accuracy",
            # topic_scope, a bi-encoder: the share of inputs whose nearest taxonomy node
            # was the right one. Not comparable with either of the others, which is the
            # reason this list is an allow-list rather than a free string.
            "top1_accuracy",
        ), name


# --------------------------------------------------- silence over staleness


def test_a_detector_that_is_not_built_carries_no_numbers(
    performance: dict[str, Any],
) -> None:
    """Stale figures are the failure this prevents.

    A page that shows last week's accuracy for a detector whose weights no longer load
    is claiming a check runs when it does not, which is the thing this project refuses
    everywhere else.
    """
    for name, entry in performance["detectors"].items():
        if entry["status"] != "built":
            assert entry["metrics"] is None, f"{name} is not built but carries metrics"
            assert entry.get("why_not_built"), (
                f"{name} is not built and does not say why"
            )


def test_status_is_one_of_two_things(performance: dict[str, Any]) -> None:
    for name, entry in performance["detectors"].items():
        assert entry["status"] in ("built", "not built"), name


# ------------------------------------------------------------ caveats travel


def test_a_zero_score_explains_itself(performance: dict[str, Any]) -> None:
    """Zero is the number most likely to be quoted and least likely to be understood.

    toxicity scores zero in Maltese because Maltese is absent from XLM-RoBERTa's
    pretraining, which no amount of training data changes. A reader seeing the zero
    without that sentence would reasonably conclude the corpus was at fault.
    """
    for name, entry in scored(performance).items():
        for code, row in entry["metrics"]["per_language"].items():
            if row["score"] == 0.0:
                assert row.get("notes"), (
                    f"{name}/{code} scores zero with no explanation attached"
                )


def test_a_thin_sample_says_so(performance: dict[str, Any]) -> None:
    for name, entry in scored(performance).items():
        for code, row in entry["metrics"]["per_language"].items():
            if row["n"] is not None and row["n"] < THIN_SUPPORT:
                joined = " ".join(row.get("notes", []))
                assert "only" in joined, (
                    f"{name}/{code} rests on {row['n']} examples and does not say so"
                )


def test_a_detector_with_thin_languages_carries_a_summary_caveat(
    performance: dict[str, Any],
) -> None:
    # Per-language notes are for a reader looking at one row. The detector-level caveat
    # is for a reader looking at the headline, which is the more common case.
    for name, entry in scored(performance).items():
        thin = [
            code
            for code, row in entry["metrics"]["per_language"].items()
            if row["n"] is not None and row["n"] < THIN_SUPPORT
        ]
        if thin:
            assert entry["caveats"], (
                f"{name} has {len(thin)} thin languages and no caveat"
            )


def test_the_file_tells_a_reader_how_to_read_it(performance: dict[str, Any]) -> None:
    # Because the most likely consumer is somebody building a page, in a hurry, who will
    # read exactly one sentence.
    assert "n" in performance["reading_this"]
    assert performance["generated_by"] == "benchmarks/collect.py"


# ------------------------------------------------------------------------- md agrees


def test_the_markdown_matches_the_json(performance: dict[str, Any]) -> None:
    """Regenerated from the same data and compared, so the two cannot drift.

    The same pattern `tests/test_reference.py` uses for docs/detectors.md.
    """
    if not PERFORMANCE_MD.exists():
        pytest.skip("performance.md not generated")

    import sys

    sys.path.insert(0, str(REPO / "benchmarks"))
    from collect import to_markdown  # type: ignore[import-not-found]

    assert to_markdown(performance) == PERFORMANCE_MD.read_text(encoding="utf-8"), (
        "docs/reference/performance.md is out of date. Regenerate with "
        "`uv run python benchmarks/collect.py --artifacts <dir>`."
    )


def test_the_markdown_never_shows_a_score_without_a_sample_count(
    performance: dict[str, Any],
) -> None:
    # The rendered table has to carry the count too, not only the JSON behind it.
    if not PERFORMANCE_MD.exists():
        pytest.skip("performance.md not generated")
    text = PERFORMANCE_MD.read_text(encoding="utf-8")
    if scored(performance):
        assert "Test cases" in text


# --------------------------------------------------------------------------- latency


def test_latency_names_the_input_it_was_measured_on(
    performance: dict[str, Any],
) -> None:
    # A latency figure with no input length attached is the exact defect the budget work
    # existed to fix. It must not come back through this file.
    latency = performance["latency"]
    assert latency["reference_input"]["characters"] > 0
    assert latency["threads"] == 1
    assert latency["provider"] == "CPUExecutionProvider"


def test_the_reference_input_is_the_one_the_budgets_use(
    performance: dict[str, Any],
) -> None:
    from test_budgets import REFERENCE_INPUT

    assert performance["latency"]["reference_input"]["characters"] == len(
        REFERENCE_INPUT
    )


def test_every_built_detector_has_a_latency_figure(performance: dict[str, Any]) -> None:
    from flowx_border.registry import loaded_detectors

    measured = set(performance["latency"]["per_detector_ms"])
    # Compared against the file's own status rather than against the live registry, so
    # this does not fail merely because the machine running the tests has different
    # weights available from the machine that generated the file.
    built = {n for n, e in performance["detectors"].items() if e["status"] == "built"}
    assert built <= measured or not loaded_detectors(), sorted(built - measured)
